== Solution written in elm 0.19

goto https://guide.elm-lang.org/install.html to find your elm installation guide

to build:

    elm make src/Main.elm

This should produce index.html in the root directory, which you can open locally (also checked in for convenience).

== Input

The input is a string, which we convert to a character array.

=== Part 1

These are the steps of my solution:
The idea is to 

  . iterate over the polymer with two pointers: first one walks from character to character, second one points at last entry not yet folded
  . store the indicies of the characters that reacted (making a black list of characters)
  . we use this black list in each run to determine what the last character was that hasn't reacted yet  
  . in the end, we can subtract the number of reacted indicies from the original polymer length

=== Part 2

My algorithm is really slow here, my solution brute force:

  . find all characters that appear at least once in the input data (a set of characters to try and remove) => the candidates
  . iterate over each candidate character 
    .. remove it from the input data
    .. use the reduction of part1 and measure the length of the resulting polymer
  . get the minimum length for all candidates => solution

