== Recursive Approach
I parse the text straight into an array of integers. That's easiest.
All the hard work happens in my Node class. When you create a Node, you pass the number array and where to start. This then recursively creates further Node objects and adds them as children. Each Node contains an array of its meta data and an Int pointer to where its entry ends in the number array. That's the trick how traversing back the recursion I know where to continue in the levels up.
I also have a flat List of nodes to easily do the work for part 1. The tree structure is required for part 2.

== Calulating Results
Part 1 is simple once the data has been read in the Node objects. Just use reduce() on the Node list to add all the meta data entries, using reduce() also on the individual lists.
I have to say I really like how I can apply closures to collections.

Part 2 is a recursive solution again. I ask the root Node to calculate its value and it in turn does that with its children.

And because the logic is all in the Node class, my main code is pretty simple for solving the two parts:

[source, swift]
print("08-01: " + String(Node.nodeList.reduce(0, {curSum, n in n.metaData.reduce(curSum, { x, m in x + m})})))
print("08-02: " + String(nodeTree.Value()))

== Running
If you want to run it, call Puzzle8() from your main or use a playground
