== Solution written in elm 0.19

goto https://guide.elm-lang.org/install.html to find your elm installation guide

to build:

    elm make src/Main.elm

This should produce index.html in the root directory, which you can open locally (also checked in for convenience).

== Input

The input is a string, which we convert to a character array.

=== Part 1

These are the steps of my solution:
The idea is to 

  . build a graph using the Dict type:
    .. for each node as KEY (encoded as Int), we remember the 'following values' according to the input (VALUES, as List Int)
  . additionally, we have a Set that remembers all pairs (Int, Int) of (after <- before) edges in the graph, i.e. the prerequisites that must be done before a node can be handled next
  . we traverse that graph, starting with all the nodes that have no prerequisite, sorted ascending (consider it a stack)
    .. we start with the first, remove it is a prerequisite and lookup its children that don't have any prerequisites left
    .. we add the children to the stack (sorting it again to keep the stack ability)
    .. we recurse, until the stack is empty

=== Part 2

pending

