
**https://adventofcode.com/2018/day/15[rtfChallenge]**

LOL

== Architecture

Braindump of classes I might need..

[plantuml, day15-class, png]
....
@startuml
skinparam defaulttextalignment center
skinparam monochrome true
skinparam shadowing false
class Arena {
  lines []string
  fighters []*Fighter
  +//bool// isOccupied(pos Position)
  +//int// distance(fighter *Fighter, dest Position)
  +//[]Position// path(fighter *Fighter, dest Position)
  //*self// print()
  //*self// addFighter(f *Fighter)
  //[]*Fighter// getGoblins()
  //[]*Fighter// getElves()
}

class Fighter {
	id string
	pos Position
	hp int
	power int
  alliance string // elf, goblin
  //*self// takeDamage(power int)
  //*self// move(pos Position)
  +//*self// attack(target *Fighter)
}

class Position {
  x int
  y int
  +//bool// isOccupied(arena *Arena)
}

class Game {
  arena Arena
  roundsPlayed int
  +//*self// round()
}

Game o-- Arena
Arena o-- Fighter
Fighter -- Position
Arena -- Position
@enduml
....

== Part 1



== Part 2

oh god..

== Run solution

1. Get into directory of this README
1. Set gopath to current dir `export GOPATH=$PWD`
1. Install dependency `go get github.com/satori/go.uuid`
1. `cd src`
1. `go build -o game && ./game`
1. Profit
