//some attributes to make the file more readable

:rdmueller: image:https://avatars2.githubusercontent.com/u/1856308?s=40[link=https://github.com/rdmueller]
:anoff: image:https://avatars2.githubusercontent.com/u/7142618?s=40[link=https://github.com/anoff]
:robertwalter83: image:https://avatars2.githubusercontent.com/u/5462981?s=40[link=https://github.com/robertwalter83]
:gysel: image:https://avatars0.githubusercontent.com/u/1065960?s=40[link=https://github.com/gysel]
:tschulte: image:https://avatars1.githubusercontent.com/u/203910?s=40[link=https://github.com/tschulte]
:olithissen: image:https://avatars1.githubusercontent.com/u/13063051?s=40[link=https://github.com/olithissen]

== Today I learned..

A collection of everyones daily learnings

=== Day 1

[cols="1,10"]
|====
|{anoff}
a| * .. that Go only has for loops

|{rdmueller}
a| * Elm is a language which seems to compile / transpile to JavaScript

|{robertwalter83}
a| * I learned how to use List.foldl/foldr in elm

|{gysel}
a| * How to create an infinite, repeating Sequence in Kotlin.
 * There is no map operator that also provides an accumulator in Kotlin (such as http://reactivex.io/documentation/operators/scan.html[ReactiveX Scan])

|{tschulte}
a| * How to read a file in JavaScript and split by line ending
   * That JavaScript may implicitly convert a string to a number (e.g. that `1 + "1" == "11"` but `1 * "1" === 1`)
   * How to explicitly convert a string to a number using `Number("1")`
   * That `Number("")` and `Number(null)` both are `0`
   * That `NaN !== NaN`, but you have to use `isNaN(NaN)` instead
|====

=== Day 2

[cols="1,10"]
|====
|{anoff}
a| * .. all my go projects need to go into `~/go/src`, which solves the dependency link problem for go

|{rdmueller}
a| * Documentation driven development: first write the docs, then do the coding.
Works great on top of test driven development!
* Python has no power-assertions like groovy has. Makes testing harder 😒
* VS Code and thus gitlab has a column mode for editing!
* All your tests might run fine but the solution is still wrong

|{robertwalter83}
a| * that it is hard to drop the imperative mindset if you are used to it too much

|{gysel}
a| * The zip operator in Kotlin combines two Lists into a List<Pair>>
* It makes sense to return either List or Sequence from your functions depending on the result size (List or Stream in Java)

|====

=== Day 3

[cols="1,10"]
|====
|{rdmueller}
a| * how classes work in Python
* Asciidoctor lets you https://asciidoctor.org/docs/user-manual/#tag-filtering[exclude tags] in the `include` statement

|{anoff}
a| * .. https://gobyexample.com/structs[structs] and https://gobyexample.com/maps[maps] are super powerful 🤯
 * ..go is fast 💨

|{olithissen}
a| * Get the test input working first and assert that the results match the example

|{robertwalter83}
a| * that parsing the input data is sometimes the most challenging part of these early tasks


|====

=== Day 4

[cols="1,10"]
|====
|{anoff}
a| * being able to increment a non-existant integer value without checking for its existence first is super convenient
* splitting strings is easier than regexing

|{rdmueller}
a| * how to create your own python modules

|{gysel}
a| * you can destructure in Kotlin from an Array, a List, or e Map.Entry (and probably more...)
* Kotlin's `Iterable<T>.groupingBy` offers a nice way to group and then aggregate.
* How to use `fold` with a stateful accumulator

|{olithissen}
a| * Sometimes you spend so much time on a solution that you are afraid to start over again
* I started measuring function execution performance
* Once you solved a task, add asserts for your correct answers so you don't mess up during optimization

|{robertwalter83}
a| * that the elm compiler is awesome
* how to effectivley use elm's REPL

|====


=== Day 5

[cols="1,10"]
|====
|{anoff}
a| * if you struggle with a problem, **take a break**, clear your head and get a new perspective
* never assume any part of your code is too simple to have an error
* pipes do not __only__ split on new lines - also if chunks are too large

|{olithissen}
a| * Wake up, read the task, get a rough plan while falling asleep again
* Javascripts `Array.splice()` is blazingly fast and works in-place
* Loops are costly. Knowing what you are doing can make your code faster (In this case: From 3,960 msec to 360 msec)
* Get feedback! Hints from {anoff} and {rdmueller} helped cut another 60 msec

|====

=== Day 6

[cols="1,10"]
|====
|{anoff}
a| * unit tests in Go feel really verbose to write (no assertions only failure checking)
* writing modular/cleaner code seems to result in more loops than necessary
* (again) structs and maps are profit!

|====

=== Day 7

[cols="1,10"]
|====
|{anoff}
a| * graphs are fun but are super headache if you don't have 📝 (or experience)
* finally figured out that the regexp function I always need (get matches): https://golang.org/pkg/regexp/#Regexp.FindStringSubmatch[FindStringSubmatch]
* you can implement a simple queue in `Go` using a slice and
** `el := q[0]; q = q[1:]` to pop an element from top
** `el := q[i]; q = append(q[:i], q[i+1:]...)` to remove an element in the middle
* Go has a `...` spread operator

|====

=== Day 8
[cols="1,10"]
|====
|{robertwalter83}
a| * That, even after all these years, recursion can still cause a knot in my brain
* immutable data can sometimes be a burden

|====

=== Day 11

[cols="1,10"]
|====
|{anoff}
a| * Go unit tests need to start with `func Test<Name>` whereas `Name` needs to be capitalized, otherwise *NOTHING* happens 😡 https://golang.org/pkg/testing/[rtfm]

|{rdmueller}
a| * there is no asciidoctor plugin for xcode!
* today's solution part 2 is too slow to finish, but the solution already showed up after a few iterations 😎
|====
